spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-user:passEureka24@localhost:8761/eureka
    register-with-eureka: true
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log