spring:
  application:
    name: mscartoes

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1